//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 12:59:42 AM GMT 
//


package uk.co.greenjam.jrgfinance.core.servlets.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.greenjam.jrgfinance.core.servlets.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.greenjam.jrgfinance.core.servlets.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AfData }
     * 
     */
    public AfData createAfData() {
        return new AfData();
    }

    /**
     * Create an instance of {@link AfData.AfUnboundData }
     * 
     */
    public AfData.AfUnboundData createAfDataAfUnboundData() {
        return new AfData.AfUnboundData();
    }

    /**
     * Create an instance of {@link AfData.AfUnboundData.Data }
     * 
     */
    public AfData.AfUnboundData.Data createAfDataAfUnboundDataData() {
        return new AfData.AfUnboundData.Data();
    }

}
